import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const homeSource = readFileSync(resolve(process.cwd(), "client/src/pages/Home.tsx"), "utf8");

describe("Route map interactions", () => {
  it("connects place search, current location, and sheet states to the map screen", () => {
    expect(homeSource).toContain("new google.maps.places.PlacesService(map)");
    expect(homeSource).toContain("service.textSearch");
    expect(homeSource).toContain("navigator.geolocation.getCurrentPosition");
    expect(homeSource).toContain("error.PERMISSION_DENIED");
    expect(homeSource).toContain("setIsLocationPermissionHelpOpen(true)");
    expect(homeSource).toContain("RECENT_SEARCHES_KEY");
    expect(homeSource).toContain("route-recent-searches");
    expect(homeSource).toContain("getUrl({ maxWidth: 720, maxHeight: 480 })");
    expect(homeSource).toContain("getPlacePhotos(selectedPlace)");
    expect(homeSource).toContain("removeRecentSearch");
    expect(homeSource).toContain("clearRecentSearches");
    expect(homeSource).toContain("addSavedPlaceToCurrentCourse");
    expect(homeSource).not.toContain("route-map-current-course-add");
    expect(homeSource).not.toContain("route-sheet-place-glance");
    expect(homeSource).not.toContain("getPlaceOpeningLabel(mapPreviewPlace)");
    expect(homeSource).not.toContain("route-map-place-preview");
    expect(homeSource).toContain("openPlaceFromMap(place, marker)");
    expect(homeSource).toContain("type MapReturnState");
    expect(homeSource).toContain("captureMapReturnState");
    expect(homeSource).toContain("restoreMapFromPlaceDetail");
    expect(homeSource).toContain("setSelectedMapPinId(place.id)");
    expect(homeSource).toContain("selectedPinSvg");
    expect(homeSource).toContain("marker.setZIndex(200)");
    expect(homeSource).toContain("isMapCategoryBarOpen");
    expect(homeSource).toContain('aria-label={isMapCategoryBarOpen ? "지도 카테고리 접기" : "지도 카테고리 펼치기"}');
    expect(homeSource).toContain("isNearbyCategoryPickerOpen");
    expect(homeSource).toContain('aria-label={isNearbyCategoryPickerOpen ? "주변 추천 카테고리 접기" : "주변 추천 카테고리 펼치기"}');
    expect(homeSource).toContain('const keepFullscreen = isMapFullscreen && screen === "map"');
    expect(homeSource).toContain('if (!keepFullscreen) setSheetMode("expanded")');
    expect(homeSource).toContain('setSheetMode("expanded")');
    expect(homeSource).toContain('setSheetMode((mode) => {');
    expect(homeSource).toContain('sheetMode !== "hidden"');
    expect(homeSource).toContain("currentLocationPinSvg");
    expect(homeSource).toContain('route-map-screen sheet-${sheetMode}${isMapFullscreen');
    expect(homeSource).toContain("new google.maps.places.AutocompleteService()");
    expect(homeSource).toContain("service.getPlacePredictions");
    expect(homeSource).toContain("map.panTo({ lat: place.lat, lng: place.lng })");
    expect(homeSource).toContain("categoryPinColor(place.category)");
    expect(homeSource).toContain("service.getDetails");
    expect(homeSource).toContain('fields: ["name", "formatted_address", "formatted_phone_number", "opening_hours", "photos", "website"]');
    expect(homeSource).toContain("getUrl({ maxWidth: 1200, maxHeight: 900 })");
    expect(homeSource).toContain("route-photo-gallery-overlay");
    expect(homeSource).toContain("route-discovery-controls");
    expect(homeSource).toContain("syncMapMarkers(map, visibleMapPlaces)");
    expect(homeSource).toContain("syncMapMarkers(mainMapRef.current, visibleMapPlaces)");
    expect(homeSource).toContain("openCoursePicker");
    expect(homeSource).toContain("route-home-course-start");
    expect(homeSource).toContain("naverReservationUrl");
    expect(homeSource).toContain("naverMapSearchUrl");
    expect(homeSource).toContain("renderScheduleWarnings(selectedCourseScheduleWarnings)");
    expect(homeSource).toContain('courseStatusLabel[selectedCourse.status || "planned"]');
    expect(homeSource).toContain('hours: item.hours || ""');
    expect(homeSource).toContain("hours: place.hours");
    expect(homeSource).toContain("hours: coursePickerPlace.hours");
    expect(homeSource).toContain("dayNumber: courseItemDays[place.id] || 1");
    expect(homeSource).toContain("durationMinutes: Number(courseDurations[place.id]) || 60");
    expect(homeSource).toContain('aria-label="일차별 일정"');
    expect(homeSource).toContain("route-draggable-place");
    expect(homeSource).toContain("estimateRouteSegments");
    expect(homeSource).toContain("getRouteEfficiencyWarnings");
    expect(homeSource).toContain('aria-label="장소 간 예상 이동시간"');
    expect(homeSource).toContain("activeDetailStops");
    expect(homeSource).toContain("route-day-map-context");
    expect(homeSource).toContain("copyCourseShareLink");
    expect(homeSource).toContain("exportCourseImage");
    expect(homeSource).toContain("setClusterPreviewPlaces(group.points)");
    expect(homeSource).toContain('aria-label="클러스터 장소 목록"');
    expect(homeSource).toContain("toggleRecentRegionFavorite");
    expect(homeSource).toContain('aria-label="최근 탐색 지역"');
    expect(homeSource).toContain("tutorialSpotlightMarkerRef");
    expect(homeSource).toContain('title: isClusterStep ? "튜토리얼: 겹친 장소 클러스터"');
    expect(homeSource).toContain('aria-label="예시 코스"');
    expect(homeSource).toContain("route-tutorial-example-route");
    expect(homeSource).toContain("const nearbyOrigin = userLocation || selectedRegion");
    expect(homeSource).toContain("}).sort((a, b) => distanceInMeters(origin, a) - distanceInMeters(origin, b))");
    expect(homeSource).toContain("function loadNearbyPlaces(origin");
    expect(homeSource.indexOf("function categoryFromPlaceTypes")).toBeLessThan(homeSource.indexOf("function loadNearbyPlaces"));
    expect(homeSource).toContain('loadNearbyPlaces(location, "전체", true)');
    expect(homeSource).toContain('const searchTypes = category === "전체" ? ["tourist_attraction", "restaurant", "cafe"]');
    expect(homeSource).toContain('aria-label="주변 장소 추천 카테고리"');
    expect(homeSource).toContain("loadNearbyPlaces(nearbyOrigin, category, isCurrentLocationSearch, keepFullscreen)");
    expect(homeSource).toContain('현재 위치 주변 ${filter === "전체" ? "여행지·음식점·카페"');
    expect(homeSource).toContain('aria-pressed={openNowOnly}');
    expect(homeSource).toContain("현재 영업 중");
    expect(homeSource).toContain('fields: ["opening_hours", "rating", "user_ratings_total"]');
    expect(homeSource).toContain("weekday_text");
    expect(homeSource).toContain("getGooglePlaceTodayHours");
    expect(homeSource).toContain("getDisplayHours");
    expect(homeSource).toContain("getPlaceOpeningLabel");
    expect(homeSource).toContain("리뷰 ${place.reviewCount}");
  });
});
