import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const homeSource = readFileSync(resolve(process.cwd(), "client/src/pages/Home.tsx"), "utf8");

describe("Route map interactions", () => {
  it("connects place search, current location, and sheet states to the map screen", () => {
    expect(homeSource).toContain("new google.maps.places.PlacesService(map)");
    expect(homeSource).toContain("service.textSearch");
    expect(homeSource).toContain("navigator.geolocation.getCurrentPosition");
    expect(homeSource).toContain("error.PERMISSION_DENIED");
    expect(homeSource).toContain("setIsLocationPermissionHelpOpen(true)");
    expect(homeSource).toContain("RECENT_SEARCHES_KEY");
    expect(homeSource).toContain("route-recent-searches");
    expect(homeSource).toContain("getUrl({ maxWidth: 720, maxHeight: 480 })");
    expect(homeSource).toContain("getPlacePhotos(selectedPlace)");
    expect(homeSource).toContain("removeRecentSearch");
    expect(homeSource).toContain("clearRecentSearches");
    expect(homeSource).toContain("addSavedPlaceToCurrentCourse");
    expect(homeSource).toContain("route-map-current-course-add");
    expect(homeSource).toContain("route-sheet-place-glance");
    expect(homeSource).toContain("mapPreviewPlace.hours");
    expect(homeSource).toContain('setSheetMode("expanded")');
    expect(homeSource).toContain('setSheetMode((mode) => {');
    expect(homeSource).toContain('sheetMode !== "hidden"');
    expect(homeSource).toContain("currentLocationPinSvg");
    expect(homeSource).toContain('route-map-screen sheet-${sheetMode}${isMapFullscreen');
    expect(homeSource).toContain("new google.maps.places.AutocompleteService()");
    expect(homeSource).toContain("service.getPlacePredictions");
    expect(homeSource).toContain("map.panTo({ lat: place.lat, lng: place.lng })");
    expect(homeSource).toContain("categoryPinColor(place.category)");
    expect(homeSource).toContain("service.getDetails");
    expect(homeSource).toContain('fields: ["name", "formatted_address", "formatted_phone_number", "opening_hours", "photos", "website"]');
    expect(homeSource).toContain("getUrl({ maxWidth: 1200, maxHeight: 900 })");
    expect(homeSource).toContain("route-photo-gallery-overlay");
    expect(homeSource).toContain("route-discovery-controls");
    expect(homeSource).toContain("syncMapMarkers(map, visibleMapPlaces)");
    expect(homeSource).toContain("syncMapMarkers(mainMapRef.current, visibleMapPlaces)");
    expect(homeSource).toContain("openCoursePicker");
    expect(homeSource).toContain("route-home-active-trip");
    expect(homeSource).toContain("naverReservationUrl");
    expect(homeSource).toContain("naverMapSearchUrl");
    expect(homeSource).toContain("renderScheduleWarnings(selectedCourseScheduleWarnings)");
    expect(homeSource).toContain("courseStatusLabel[courseStatus]");
    expect(homeSource).toContain('hours: item.hours || "영업시간 확인"');
    expect(homeSource).toContain("hours: place.hours");
    expect(homeSource).toContain("hours: coursePickerPlace.hours");
    expect(homeSource).toContain("dayNumber: courseItemDays[place.id] || 1");
    expect(homeSource).toContain("durationMinutes: Number(courseDurations[place.id]) || 60");
    expect(homeSource).toContain('aria-label="일차별 일정"');
    expect(homeSource).toContain("route-draggable-place");
    expect(homeSource).toContain("estimateRouteSegments");
    expect(homeSource).toContain("getRouteEfficiencyWarnings");
    expect(homeSource).toContain('aria-label="장소 간 예상 이동시간"');
    expect(homeSource).toContain("activeDetailStops");
    expect(homeSource).toContain("route-day-map-context");
    expect(homeSource).toContain("copyCourseShareLink");
    expect(homeSource).toContain("exportCourseImage");
    expect(homeSource).toContain("setClusterPreviewPlaces(group.points)");
    expect(homeSource).toContain('aria-label="클러스터 장소 목록"');
    expect(homeSource).toContain("toggleRecentRegionFavorite");
    expect(homeSource).toContain('aria-label="최근 탐색 지역"');
    expect(homeSource).toContain("tutorialSpotlightMarkerRef");
    expect(homeSource).toContain('title: isClusterStep ? "튜토리얼: 겹친 장소 클러스터"');
    expect(homeSource).toContain('aria-label="예시 코스"');
    expect(homeSource).toContain("route-tutorial-example-route");
    expect(homeSource).toContain("const nearbyOrigin = userLocation || selectedRegion");
    expect(homeSource).toContain("normalized.sort((a, b) => distanceInMeters(origin, a) - distanceInMeters(origin, b))");
  });
});
